name: "Hello world workflow"

on:
  push:
  
jobs:
  print_hello_world_ubuntu:
    name: Hello world Ubuntu!
    runs-on: ubuntu-latest
    
    steps:
      - name: Hello world Ubuntu!
        run: 'date'
        
  print_hello_world_windows:
    name: Hello world Windows!
    runs-on: windows-latest
    
    steps:
      - name: Hello world Windows!
        run: 'date'
        
  print_hello_world_macos:
    name: Hello world MacOS!
    runs-on: macos-latest
    
    steps:
      - name: Hello world MacOS!
        run: 'date'
